export type MovimientoCajaDto = {
  id: string;
  tipo: string;
  concepto?: string | null;
  medio: 'Efectivo' | 'Tarjeta' | 'Transferencia' | 'Mixto' | string;
  total: number;
  montoEfectivo?: number | null;
  montoTransferencia?: number | null;
  abono?: number | null;
  mora?: number | null;
  cobradorId?: string | null;
  corteCajaId?: string | null;
  recibidoCaja?: boolean;
  estatusFichaFinanzas?: 'PENDIENTE' | 'COBRADO' | 'EN_CORTE' | null;
  creditoId?: string | null;
  numeroFicha?: number | null;
  fecha: string;
  hora?: string | null;
  registraCaja?: boolean;
};
